import { Link } from "react-router-dom";
import { LegalDoc, Section } from "./LegalDoc.jsx";
import PageMeta from "../components/PageMeta.jsx";

export default function Terms() {
  return (
    <LegalDoc title="Terms of Service" updated="11 July 2026">
      <PageMeta title="Terms of Service — Graspr" description="The terms governing your use of Graspr for CAT VARC practice." />
      <p>
        These terms govern your use of Graspr, operated by Tarun Gupta, an individual based in
        Bangalore, Karnataka, India. By creating an account, you agree to them. If you don't
        agree, please don't use Graspr.
      </p>

      <Section title="Eligibility">
        <p>
          You must be 18 years of age or older to create a Graspr account. By registering, you
          confirm that you meet this requirement.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You're responsible for keeping your password confidential and for all activity under
          your account. Tell us immediately if you suspect unauthorized access. Provide accurate
          information when registering — a username and a real, working email address.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>Don't use Graspr to:</p>
        <ul className="ml-4 list-disc space-y-1.5">
          <li>Attempt to bypass rate limits, scrape content at scale, or automate account creation.</li>
          <li>Submit content (question flags, bio, article text) that's abusive, illegal, or infringes someone else's rights.</li>
          <li>Interfere with the security or normal operation of the service.</li>
          <li>Share your account or resell access to it.</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these terms.</p>
      </Section>

      <Section title="AI-generated feedback isn't guaranteed correct">
        <p>
          Graspr uses AI to evaluate the quality of your written reasoning and to power AI Coach's
          Socratic dialogue. This feedback is generated by a third-party language model and,
          despite our best efforts, may occasionally be inaccurate, incomplete, or inconsistent.
          The correct answer to a question is always determined by Graspr's own question data, not
          by the AI — but the explanations, scores, and coaching commentary are AI-generated and
          should be treated as a study aid, not an authoritative or infallible source. Use your own
          judgment.
        </p>
      </Section>

      <Section title="Ownership">
        <p>
          Graspr's platform, questions, passages, and design are our intellectual property. Text
          you submit — reasoning explanations, bio, question-flag notes — remains yours; by
          submitting it you grant us a license to store, process, and display it back to you as
          part of the service (including sending it to our AI provider to generate feedback, as
          described in our{" "}
          <Link to="/privacy" className="fx-underline font-semibold" style={{ color: "var(--teal)" }}>Privacy Policy</Link>).
          We don't claim ownership of your reasoning text beyond what's needed to run the service.
        </p>
      </Section>

      <Section title="No guarantee of exam outcomes">
        <p>
          Graspr is a practice tool. We make no promises about your CAT (or any exam) score,
          admission outcomes, or that using Graspr will improve your results.
        </p>
      </Section>

      <Section title="Termination">
        <p>
          You can delete your account at any time from the Profile menu — this is immediate and
          permanent. We may suspend or terminate your access if you violate these terms, and we'll
          make a reasonable effort to tell you why.
        </p>
      </Section>

      <Section title="Disclaimer & limitation of liability">
        <p>
          Graspr is provided "as is," without warranties of any kind, express or implied. To the
          maximum extent permitted by law, we are not liable for indirect, incidental, or
          consequential damages arising from your use of the service, including reliance on
          AI-generated feedback.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms as Graspr evolves (for example, when paid plans launch).
          We'll update the date above when we do, and for material changes, we'll make a
          reasonable effort to notify you directly.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by the laws of India. Any dispute arising from these terms or
          your use of Graspr is subject to the exclusive jurisdiction of the courts of Bangalore,
          Karnataka.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Questions about these terms:{" "}
          <a href="mailto:privacy@graspr.in" className="fx-underline font-semibold" style={{ color: "var(--teal)" }}>privacy@graspr.in</a>.
        </p>
      </Section>
    </LegalDoc>
  );
}
